export const CATEGORIES = [
  "All Categories",
  "Fashion",
  "Tech",
  "Beauty",
  "Fitness",
  "Food",
  "Travel",
  "Luxury",
  "Gaming",
];

export const SAMPLE_INFLUENCERS = [
  {
    id: "1",
    name: "Priya Sharma",
    handle: "@priyasharma",
    category: "Fashion",
    followers: 125000,
    engagement: 4.8,
    fee: 45000,
    image: "https://ui-avatars.com/api/?name=Priya+Sharma&background=8B5CF6&color=fff",
  },
  {
    id: "2",
    name: "Arjun Mehta",
    handle: "@techarjun",
    category: "Tech",
    followers: 230000,
    engagement: 3.2,
    fee: 62000,
    image: "https://ui-avatars.com/api/?name=Arjun+Mehta&background=8B5CF6&color=fff",
  },
  {
    id: "3",
    name: "Neha Kapoor",
    handle: "@nehabeauty",
    category: "Beauty",
    followers: 98000,
    engagement: 5.7,
    fee: 38000,
    image: "https://ui-avatars.com/api/?name=Neha+Kapoor&background=8B5CF6&color=fff",
  },
  {
    id: "4",
    name: "Vikram Singh",
    handle: "@fitvikram",
    category: "Fitness",
    followers: 175000,
    engagement: 6.1,
    fee: 52000,
    image: "https://ui-avatars.com/api/?name=Vikram+Singh&background=8B5CF6&color=fff",
  },
  {
    id: "5",
    name: "Ananya Desai",
    handle: "@foodieananya",
    category: "Food",
    followers: 88000,
    engagement: 7.2,
    fee: 35000,
    image: "https://ui-avatars.com/api/?name=Ananya+Desai&background=8B5CF6&color=fff",
  },
  {
    id: "6",
    name: "Rahul Verma",
    handle: "@travelwithrahul",
    category: "Travel",
    followers: 320000,
    engagement: 4.5,
    fee: 78000,
    image: "https://ui-avatars.com/api/?name=Rahul+Verma&background=8B5CF6&color=fff",
  },
  {
    id: "7",
    name: "Meera Rajput",
    handle: "@luxurymeera",
    category: "Luxury",
    followers: 110000,
    engagement: 3.8,
    fee: 95000,
    image: "https://ui-avatars.com/api/?name=Meera+Rajput&background=8B5CF6&color=fff",
  },
  {
    id: "8",
    name: "Aditya Kumar",
    handle: "@gamingadi",
    category: "Gaming",
    followers: 420000,
    engagement: 8.3,
    fee: 85000,
    image: "https://ui-avatars.com/api/?name=Aditya+Kumar&background=8B5CF6&color=fff",
  },
];
